---
  extends: 'xo-space'
  env:
    node: true
    browser: true
  rules:
    comma-dangle:
      - 2
      - always-multiline
    object-curly-spacing:
      - 2
      - always
    react/jsx-uses-react: 1
    react/jsx-uses-vars: 1
  globals:
    chrome: true
  plugins:
      - react
